# Generated by Django 3.1.2 on 2020-12-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pair_work', '0002_auto_20201129_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='user_id',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
