# Generated by Django 3.1.2 on 2020-12-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pair_work', '0003_work_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='reached_at',
            field=models.DateTimeField(null=True, verbose_name='reached_at'),
        ),
    ]
