# Generated by Django 3.1.2 on 2020-12-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pair_work', '0004_work_reached_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='reached_at',
        ),
        migrations.AddField(
            model_name='work',
            name='will_reach_at',
            field=models.DateTimeField(null=True, verbose_name='will_reach_at'),
        ),
    ]
