# Generated by Django 3.1.2 on 2020-12-26 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pair_work', '0005_auto_20201224_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_id', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('text', models.CharField(max_length=280)),
            ],
        ),
    ]
