# Generated by Django 3.1.2 on 2020-12-26 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pair_work', '0006_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='is_end',
            field=models.BooleanField(default=False),
        ),
    ]
