# Generated by Django 3.1.2 on 2020-12-26 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pair_work', '0007_goal_is_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='month_id',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
