# Generated by Django 3.1.2 on 2020-12-26 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pair_work', '0008_goal_month_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='text',
            new_name='goal',
        ),
    ]
