# Generated by Django 3.1.2 on 2020-12-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pair_work', '0009_auto_20201226_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal',
            field=models.CharField(max_length=280, null=True),
        ),
    ]
