# Generated by Django 3.1.2 on 2021-01-02 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pair_work', '0010_auto_20201226_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='will_reach_at',
        ),
        migrations.AddField(
            model_name='work',
            name='deadline',
            field=models.DateTimeField(null=True, verbose_name='deadline'),
        ),
    ]
